Better "dark mode" support
freedomofpress/dangerzone pull request #550
Opened 2023-09-23 03:25 UTC by garrettr

Fixes #528—but for all platforms, not just macOS. I believe this approach should work on all platforms that provide an OS setting for a system-wide light or dark color mode, *but I have only tested this change on macOS*.

I decided to go with an approach that would work on both PySide2/Qt 5 and PySide6/Qt 6. If you want, I'm happy to file follow-up issues for:
1. Switching to `QGuiApplication.styleHints().colorScheme()`, only supported in Qt 6.5+.
2. Handling the (likely rare in typical usage) case where the user changes the OS color setting while the Dangerzone GUI is running, which requires the `colorSchemeChanged` signal added in Qt 6.5.

## Before this change

### Light Mode

<img width="712" alt="Screenshot 2023-09-22 at 15 32 38" src="https://github.com/freedomofpress/dangerzone/assets/407302/d182a2c6-910f-4828-acbb-08212daf0684">

### Dark Mode

<img width="712" alt="Screenshot 2023-09-22 at 15 33 33" src="https://github.com/freedomofpress/dangerzone/assets/407302/9bda447f-ef00-4d65-9e47-aeea585b203e">

Exhibits the issues described in #528.

## After this change

### Light Mode

<img width="712" alt="Screenshot 2023-09-22 at 22 46 01" src="https://github.com/freedomofpress/dangerzone/assets/407302/7a98c4d8-b257-4c1d-a7a9-7c48f07c0816">

Looks the same as Light Mode before this change.

### Dark Mode

<img width="712" alt="Screenshot 2023-09-22 at 22 48 08" src="https://github.com/freedomofpress/dangerzone/assets/407302/d6130a57-6b87-4b93-9137-cfb5b2693eae">

Fixes the issues described in #528 and adds a custom style for `QLabel[style="safe_extension_filename"]` in dark mode that's consistent with the preexisting custom appearance in Light Mode.

2023-09-25 14:01 UTC, deeplow requested changes
Thanks a lot for the contribution. It looks pretty solid to merge. I just have one suggestion to move the code to somewhere where it's easier to test the application logic.

I was also playing around a bit with the PySide6 [`QtGui.QStyleHints.colorScheme()`](https://doc.qt.io/qtforpython-6/PySide6/QtGui/QStyleHints.html#id0) and it's not very reliable. So I think it's best to go with the strategy you suggested, even in systems where PySide6 is available.
<details>
<summary>
In my case (linux) it was unable to detect de color scheme and instead of outputting `Qt.ColorScheme.Unknown` it instead returned some random color scheme number:
</summary>

```python
>>> QtGui.QStyleHints().colorScheme()                                                                   
<ColorScheme.1634038370: 1634038370>
>>> QtCore.Qt.ColorScheme.Unknown
<ColorScheme.Unknown: 0>                                                                                
>>> QtCore.Qt.ColorScheme.Dark
<ColorScheme.Dark: 2>
>>> QtCore.Qt.ColorScheme.Light
<ColorScheme.Light: 1>
>>> QtGui.QStyleHints().colorScheme() == QtCore.Qt.ColorScheme.Unknown
False
```

</details>

2023-09-25 20:41 UTC, garrettr commented on dangerzone/gui/logic.py
> +    def infer_os_color_mode(self) -> OSColorMode:
Will do!

2023-09-26 09:42 UTC, deeplow commented
Perfect. And now almost everything in CI is passing. The only thing missing is a type error but it can be easily solved with something like this:

```diff
diff --git a/dangerzone/gui/logic.py b/dangerzone/gui/logic.py
index 3832c568..74d7d1e6 100644
--- a/dangerzone/gui/logic.py
+++ b/dangerzone/gui/logic.py
@@ -12,6 +12,8 @@ from colorama import Fore
 # FIXME: See https://github.com/freedomofpress/dangerzone/issues/320 for more details.
 if typing.TYPE_CHECKING:
     from PySide2 import QtCore, QtGui, QtWidgets
+
+    from . import Application
 else:
     try:
         from PySide6 import QtCore, QtGui, QtWidgets
@@ -35,7 +37,7 @@ class DangerzoneGui(DangerzoneCore):
     """
 
     def __init__(
-        self, app: QtWidgets.QApplication, isolation_provider: IsolationProvider
+        self, app: "Application", isolation_provider: IsolationProvider
     ) -> None:
         super().__init__(isolation_provider)
 ```

2023-09-26 14:26 UTC, deeplow commented
@garrettr I can fix the lint when merging. Do you still want to do something else or can I merge it?

2023-09-26 16:26 UTC, garrettr commented
> @garrettr I can fix the lint when merging. Do you still want to do something else or can I merge it?

I'll fix the lint!

Also, I noticed a minor issue with `poetry run make lint` when I tried to run it locally. In my local dev environment I'm using a virtualenv stored in `dangerzone/.venv`, a common configuration. When I ran `poetry run make lint` the `lint-isort` step failed with numerous errors due to unsorted imports in the source files of dependencies stored in `.venv`—see the output of the command here: [poetry_run_make_lint.txt](https://github.com/freedomofpress/dangerzone/files/12729833/poetry_run_make_lint.txt).

I would expect `isort` to ignore virtualenvs by default, and [indeed it does](https://pycqa.github.io/isort/docs/configuration/options.html#skip), but dangerzone's `pyproject.toml` has a `[tool.isort]` section that sets `skip`, so venvs are back on the menu:

```toml
[tool.isort]
profile = "black"
skip = [".gitignore"]
```

I can fix the problem by simply adding `.venv` to `skip` in `pyproject.toml`. @deeplow Is that something that would be appropriate to tack on to this change, or would you prefer I create a separate issue/PR for that?

2023-09-26 16:33 UTC, apyrgio commented
Damn,  I didn't know that `--skip` had a default, which we essentially overrode. Thanks a lot for pointing that out!

To me, it seems the proper way to solve this is to convert `skip` to [`extend_skip`](https://pycqa.github.io/isort/docs/configuration/options.html#extend-skip). Does this work in your environment? If yes, feel free to send an extra commit, and we can merge it along this PR.

2023-09-26 16:42 UTC, garrettr commented
> To me, it seems the proper way to solve this is to convert `skip` to [`extend_skip`](https://pycqa.github.io/isort/docs/configuration/options.html#extend-skip). Does this work in your environment? If yes, feel free to send an extra commit, and we can merge it along this PR.

Nice! I didn't see that option while I was skimming the `isort` docs. I agree that's the best solution. I confirmed it works for me locally and added it as an extra commit to this PR.

2023-09-26 21:31 UTC, garrettr commented
@deeplow This is ready for re-review! Now that we I've fixed the few issues I think it's ready to merge.

2023-09-27 19:35 UTC, deeplow approved these changes

2023-09-27 19:59 UTC, deeplow commented
I'm afraid I messed up the rebase and force pushed to your remote branch without first having fetched the new commits. But I've managed to recover what I could. Sorry about that (Still getting the hang of merging forked dirs). If it's all good, I'll merge. Otherwise, feel free to force push from your local branch @garrettr to override my mistake.

2023-09-28 14:04 UTC, apyrgio commented
... you nerd-sniped me @deeplow :nerd_face: 

Ok, this is something that @garrettr can easily solve by force pushing his branch, or with a `git reflog` command, if he has already pulled. Same goes to you @deeplow, you can easily recover @garrettr's branch via `git reflog`.

But what about other people who have never pulled @garrettr's repo? If you don't have access (in the fs-level) to the Git repository, this is not achievable. On GitHub though...

## Git(Hub) Plumbing Galore :wrench:

Interestingly, GitHub displays this event:

> @[deeplow](https://github.com/deeplow) [force-pushed](https://github.com/freedomofpress/dangerzone/compare/050c86ab7917293135b89d43a26708ec8bf6d935..b48843b280382f3a6bfb6941eed640783ccee537) the feature/528-better-dark-mode-macos-qt5 branch from [`050c86a`](https://github.com/freedomofpress/dangerzone/commit/050c86ab7917293135b89d43a26708ec8bf6d935)to b48843b

  This tells us that `050c86a` is the latest correct commit. If we click on the URL, we can see its contents :tada:. This means that GitHub does not run `git fsck` immediately. This also means that if you accidentally push something that is sensitive and decide to force push in order to erase it, you need to also [contact GitHub](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#fully-removing-the-data-from-github) to run `fsck` on your repo :scream: . Moving on...

We can also click on the parent commit of the leaf commit, iteratively, until we reach the root of the PR. This means that we can re-construct the branch from the commits we see in the GitHub UI.

Re-creating the commits by hand though is tedious. Thankfully, GitHub has another trick upon its sleeve. If you append `.diff` to the URL of the commit, you can download a patch file. We can iteratively run `git apply` with these patch files, and recreate the original branch.

I have actually done so, and here's the diff that I see with the branch that @deeplow restored:

```diff
diff --git a/dangerzone/gui/__init__.py b/dangerzone/gui/__init__.py
index f65145b..655b13b 100644
--- a/dangerzone/gui/__init__.py
+++ b/dangerzone/gui/__init__.py
@@ -57,8 +57,6 @@ class Application(QtWidgets.QApplication):
             style = f.read()
         self.setStyleSheet(style)
         self.original_event = self.event
-        self.os_color_mode = self.infer_os_color_mode()
-        log.debug(f"Inferred {self.os_color_mode}")
 
         def monkeypatch_event(arg__1: QtCore.QEvent) -> bool:
             event = arg__1  # oddly Qt calls internally event by "arg__1"
@@ -76,6 +74,9 @@ class Application(QtWidgets.QApplication):
 
         self.event = monkeypatch_event  # type: ignore [method-assign]
 
+        self.os_color_mode = self.infer_os_color_mode()
+        log.debug(f"Inferred system color scheme as {self.os_color_mode}")
+
     def infer_os_color_mode(self) -> OSColorMode:
         """
         Qt 6.5+ explicitly provides the OS color scheme via QStyleHints.colorScheme(),
diff --git a/dangerzone/gui/logic.py b/dangerzone/gui/logic.py
index 5ea9969..74d7d1e 100644
--- a/dangerzone/gui/logic.py
+++ b/dangerzone/gui/logic.py
@@ -1,4 +1,3 @@
-import enum
 import logging
 import os
 import platform
```

The differences are minor but we should incorporate them regardless.

---

Now that I have the original branch, and we have the OK to merge, I'll squash some commits and merge them.

2023-09-28 14:40 UTC, merged

2023-09-28 19:52 UTC, garrettr commented
Sorry I didn't respond earlier to help with git! Glad to see you got it sorted. Thanks for merging! It was a pleasure working with both of you 😊.

2023-09-29 05:31 UTC, deeplow commented
Now worries and likewise! :slightly_smiling_face: